- name: ec2 route53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-026125864f002d1cd
    zone_id: Z03322182ZV3F5YEDZYG5
    domain: "surekhadevops.biz"
    # we can pass instances through command line using -e
    # instances:
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2 ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  - name: create route 53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item.item }}.{{ domain }}" # mangodb.surekhadevops.biz
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  # we are creating one record with public only for frontend
  - name: create route 53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ domain }}" # mangodb.surekhadevops.biz
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"